version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch-node-browsers
    working_directory: ~/AQA_Python
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
           python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            wget https://bintray.com/qameta/generic/download_file?file_path=io%2Fqameta%2Fallure%2Fallure%2F2.7.0%2Fallure-2.7.0.zip
            unzip download_file?file_path=io%2Fqameta%2Fallure%2Fallure%2F2.7.0%2Fallure-2.7.0.zip
            export PATH=$PATH:/home/circleci/repo/allure-2.7.0/bin
      - run:
          name: run API test
          command: |
            . venv/bin/activate
            py.test -vv -n 4 --reruns 2 test_jira_api.py --alluredir=./allure-results
      - run:
          name: run UI test
          command: |
            . venv/bin/activate
            chmod 777 ./utils/chromedriver
            py.test -vv -n 4 --reruns 2 test_ui.py --alluredir=./allure-results
      - run:
          command: allure-2.7.0/bin/allure generate -c
          when: always
      - store_artifacts:
          path: allure-report
          destination: allure-report